import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen">
          {/* Sidebar */}

            <Menu />


          {/* Main content */}
          <main className="flex-1 p-6">
            {children}
          </main>
        </div>
        
      </body>
    </html>
  );
}

function Menu(){
  return(
    <aside className="w-[15%] min-w-[160px] border-r bg-white overflow-hidden">
      <ul className="flex flex-col gap-1 p-4">
        <li>
          <Link href="/04-routing" className="side-link">
            Routing & Layout
          </Link>
        </li>
        <li>
          <Link href="/05-link" className="side-link">
            Link
          </Link>
        </li>
        <li>
          <Link href="/06-client-server" className="side-link">
            Client & Server Components
          </Link>
        </li>
        <li>
          <Link href="/07-state-events" className="side-link">
            State & Events
          </Link>
        </li>
        <li>
          <Link href="/08-loading-error" className="side-link">
            Loading & Error UI
          </Link>
        </li>
        <li>
          <Link href="/09-database" className="side-link">
            Database
          </Link>
        </li>
      </ul>
    </aside>


 

  )
}
